config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :food_items do
  	resources :orders
  end
  
  get 'home/index'

  get 'menu'		=> 'home#menu'
  get 'contact_us'	=> 'home#contact_us'

  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food_item.rb
class FoodItem < ApplicationRecord
	belongs_to :section
	validates :name, :price, presence: true
	has_many :orders
	mount_uploader :image, ImageUploader
	
	def self.search(search)
		where("name || description ILIKE ?", "%#{search}%")
	end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :food_item
  validates :quantity, presence: true, numericality: true
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :food_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/food_items_controller.rb
class FoodItemsController < ApplicationController
  before_action :set_food_item, only: [:show, :edit, :update, :destroy]

  # GET /food_items
  # GET /food_items.json
  def index
    @food_items = FoodItem.all
    if params[:search]
      @food_items = FoodItem.search(params[:search]).order("created_at DESC")
    else
      @food_items = FoodItem.all.order("created_at DESC")
    end
  end

  # GET /food_items/1
  # GET /food_items/1.json
  def show
  end

  # GET /food_items/new
  def new
    @food_item = FoodItem.new
  end

  # GET /food_items/1/edit
  def edit
  end

  # POST /food_items
  # POST /food_items.json
  def create
    @food_item = FoodItem.new(food_item_params)

    respond_to do |format|
      if @food_item.save
        format.html { redirect_to @food_item, notice: 'Food item was successfully created.' }
        format.json { render :show, status: :created, location: @food_item }
      else
        format.html { render :new }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /food_items/1
  # PATCH/PUT /food_items/1.json
  def update
    respond_to do |format|
      if @food_item.update(food_item_params)
        format.html { redirect_to @food_item, notice: 'Food item was successfully updated.' }
        format.json { render :show, status: :ok, location: @food_item }
      else
        format.html { render :edit }
        format.json { render json: @food_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /food_items/1
  # DELETE /food_items/1.json
  def destroy
    @food_item.destroy
    respond_to do |format|
      format.html { redirect_to food_items_url, notice: 'Food item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food_item
      @food_item = FoodItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_item_params
      params.require(:food_item).permit(:name, :description, :price, :section_id, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def menu
  	@sections = Section.all
    if params[:section_id].present?
    	@current_section = Section.find(params[:section_id])
    	@food_items = FoodItem.where(section_id: @current_section)
    else 
    	@food_items = FoodItem.all
    end

    if params[:sort_column]
      @food_items = @food_items.order("#{params[:sort_column]} #{params[:sort_direction]}")
    end
  end

  def contact_us
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@item = FoodItem.find(params[:food_item_id])
		@order = @item.orders.build
	end
	def create
		@item = FoodItem.find(params[:food_item_id])
		@order = @item.orders.build order_params

		if @order.save
			#redirect_to menu_path, flash: {success: "Thank you for your order"}
			redirect_to food_item_order_path(:id => @order.id), notice: 'Thank you for your order page'
		else
			render 'new'
		end
	end
	def order_params
		params.require(:order).permit(:quantity)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class(link_path)
		current_page?(link_path) ? "btn-primary" : ""
	end
	def menu_active(link_path)
		current_page?(link_path) ? "active" : ""
	end
end

app/helpers/food_items_helper.rb
module FoodItemsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/food_items/_form.html.erb
<%= form_with(model: food_item, local: true) do |form| %>
  <% if food_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(food_item.errors.count, "error") %> prohibited this food_item from being saved:</h2>

      <ul>
      <% food_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :food_item_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :food_item_description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :food_item_price %>
  </div>

  <div class="field">
    <%= form.label :section_id %>
    <%= form.select :section_id, Section.all.map{ |section| [section.name, section.id]}, id: :food_item_section_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/food_items/edit.html.erb
<h1>Editing Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Show', @food_item %> |
<%= link_to 'Back', food_items_path %>

app/views/food_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Food Items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @food_items.each do |food_item| %>
      <tr>
        <td><%= food_item.name %></td>
        <td><%= food_item.description %></td>
        <td><%= food_item.price %></td>
        <td><%= food_item.section.name %></td>
        <td><%= image_tag(food_item.image_url.to_s, width: "150") %></td>
        <td><%= link_to 'Show', food_item %></td>
        <td><%= link_to 'Edit', edit_food_item_path(food_item) %></td>
        <td><%= link_to 'Destroy', food_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food Item', new_food_item_path %>

app/views/food_items/new.html.erb
<h1>New Food Item</h1>

<%= render 'form', food_item: @food_item %>

<%= link_to 'Back', food_items_path %>

app/views/food_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food_item.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food_item.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food_item.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food_item.section.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@food_item.image_url.to_s, width: "450") %>
</p>

<p>
  <strong>Order:</strong>
  <%= link_to 'Add to order', new_food_item_order_path(@food_item) %>
</p>

<%= link_to 'Edit', edit_food_item_path(@food_item) %> |
<%= link_to 'Back', food_items_path %>

app/views/home/contact_us.html.erb
<h1>Contact Us</h1>
<div class="row">
	<div class="col-sm-6">
		<address>
			<strong>I Len's Cuisine</strong><br>
			18-04 Nguyen Hue Str<br>
			District 1, Ho Chi Minh City<br>
			Viet Nam<br>
			(08) 0909.00.11.22
		</address>
	</div>

	<div class="col-sm-6">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.492628385385!2d106.70265731537917!3d10.773530992323508!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f46bb9d3625%3A0xe61d093ccfdf4d52!2zMTggTmd1ecOqzINuIEh1w6rMoywgQuG6v24gTmdow6ksIFF14bqtbiAxLCBI4buTIENow60gTWluaCwgVmlldG5hbQ!5e0!3m2!1sen!2s!4v1497518063720" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
	</div>
</div>

app/views/home/index.html.erb
<h1>I Len's Cuisine</h1>
<!-- <div class="btn-group" role="group" aria-label="...">
	<%= link_to "Menu", menu_path, class: "btn btn-default" %>
	<%= link_to "Contact Us", contact_us_path, class: "btn btn-default" %>
</div> -->

app/views/home/menu.html.erb
<h1>Menu</h1>
<div class="btn-group btn-group-sm" role="group" aria-label="...">
	<%= link_to 'ALL', menu_path, class: "btn btn-default #{'btn-primary' if params[:section_id].nil?}" %>
	<% @sections.each do |section| %>
		<%= link_to section.name, menu_path(section_id: section.id), class: "btn btn-default #{active_class(menu_path(section_id: section.id))}" %>
	<% end %>
</div>
<p>
<%= form_tag nil, method: 'get', class: "form-inline" do %>
	<%= hidden_field_tag :section_id, params[:section_id] %>
	<%= select_tag :sort_column, options_for_select([ ['Name', 'name'], ['Price', 'price'] ]), class: "form-control" %>
	<%= select_tag :sort_direction, options_for_select([ ['Ascending', 'asc'], ['Descending', 'desc'] ]), class: "form-control" %>
	<%= submit_tag "Sort", class: "btn btn-default" %>
<% end %>
</p>
<% if @food_items.size == 0 %>
     <p class="text-center"> No item to display</p>
     <% else %>
     	<% @food_items.each do |item| %>
			<p><strong>name:</strong> <%= item.name %></p>
			<p><strong>description:</strong> <%= item.description %></p>
			<p><strong>price:</strong> <%= number_to_currency(item.price) %></p>
			<p><strong>section:</strong> <%= Section.find(item.section_id).name %></p>
			<p><strong>Image:</strong> <%= image_tag(item.image_url.to_s, width: "450") %></p>
			<hr>
		<% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
<div class="container-fluid">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%= root_path %>">I Len's Cuisine</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li><a href="<%= menu_path %>">Menu <span class="sr-only">(current)</span></a></li>
      <li><a href="<%= contact_us_path %>">Contact</a></li>
      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">One more separated link</a></li>
        </ul>
      </li> -->
    </ul>
    <!-- <form class="navbar-form navbar-left">
      <div class="form-group">
        <input type="text" class="form-control" placeholder="Search">
      </div>
      <button type="submit" class="btn btn-default">Submit</button>
    </form> -->

    <!-- Search logic -->
    <div class="col-sm-3 col-md-3">
      <%= form_tag(food_items_path, :method => "get", id: "search-form", class: "navbar-form") do %>
        <div class="input-group">
            <%= text_field_tag :search, params[:search], placeholder: "Search Article", class: "form-control" %>
            <div class="input-group-btn">
              <%= button_tag(type: "submit", class: "btn btn-default") do %>
                <i class="glyphicon glyphicon-search"></i>
              <% end %>
            </div>
        </div>
      <% end %>
    </div>

    <!-- <ul class="nav navbar-nav navbar-right">
      <li><a href="#">Link</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li>
    </ul> -->
  </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Icuisine</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/navbar' %>
  	<div class="container">
    	<%= yield %>
    </div>
  </body>
</html>

app/views/orders/new.html.erb
<h1>Order for <%= @item.name %> </h1>

<%= form_for [@item, @order] do |f| %>
	<% if @order.errors.present? %>
		<div class="alert alert-danger">
			<%= @order.errors.full_messages.to_sentence %>
		</div>
	<% end %>
	<div class="form-group">
		<%= f.label :Quantity %>
		<%= f.number_field :quantity, class: "form-control"%>
	</div>
	<%= f.submit nil, class: "btn btn-primary" %>
<% end %>

app/views/orders/show.html.erb
<h1>Thank you for your order</h1>